In [1]:
import numpy as np

In [3]:
# Task 1: Generate a 3x3 matrix of random integers (1 to 50) with a fixed seed
np.random.seed(10)  # Ensuring reproducibility
matrix_fixed_seed = np.random.randint(1, 51, (3, 3))
print("Matrix with fixed seed:")
print(matrix_fixed_seed)

Matrix with fixed seed:
[[10 37 16]
 [ 1 50 29]
 [26 30 49]]


In [7]:
# Task 2: Generate a 3x3 matrix of random integers (1 to 50) without setting a seed
matrix_no_seed = np.random.randint(1, 51, (3, 3))
print("\nMatrix without fixed seed:")
print(matrix_no_seed)


Matrix without fixed seed:
[[31 26 13]
 [ 2 32 37]
 [28 19 30]]


1. Running the Code Twice
- The first matrix (with a fixed seed) will always generate the same numbers whenever the code is run.
- The second matrix (without a seed) will generate different numbers every time the code is run.

2. Why Use np.random.seed(10)?
- np.random.seed(10) ensures that the random number generator produces the same sequence of numbers each time the code is executed, making the results reproducible.
- This is useful for debugging and comparing results.
3. Without Setting a Seed
- The random matrix will change every time you run the code.
- This is because the random number generator is initialized with a different starting state every time.